# Generated by Django 5.2.8 on 2025-11-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.SlugField(help_text='Identificador curto, sem espaços. Ex: robo_ixc_clientes', unique=True, verbose_name='Código interno')),
                ('module_path', models.CharField(help_text='Caminho do módulo Python onde está a automação. Ex: orquestrador.automations.sample', max_length=255, verbose_name='Módulo Python')),
                ('callable_name', models.CharField(default='run', help_text='Nome da função dentro do módulo que será executada. Ex: run, main, executar, etc.', max_length=100, verbose_name='Função')),
                ('schedule_type', models.CharField(choices=[('once', 'Pontual'), ('daily', 'Diária')], default='once', max_length=20, verbose_name='Tipo de agendamento')),
                ('run_at', models.DateTimeField(blank=True, help_text="Usado quando o tipo é 'Pontual'.", null=True, verbose_name='Data/hora única')),
                ('daily_time', models.TimeField(blank=True, help_text="Usado quando o tipo é 'Diária'. Ex: 22:30.", null=True, verbose_name='Horário diário')),
                ('start_date', models.DateField(blank=True, help_text='Primeiro dia para rodar (em diária). Opcional.', null=True, verbose_name='Início')),
                ('end_date', models.DateField(blank=True, help_text='Último dia para rodar (em diária). Opcional.', null=True, verbose_name='Fim')),
                ('is_enabled', models.BooleanField(default=True, help_text='Se desmarcado, a automação não será executada pelo agendador.', verbose_name='Ativo')),
                ('allow_manual', models.BooleanField(default=True, help_text="Se marcado, aparecerá um botão 'Executar agora' no frontend.", verbose_name='Permite disparo manual')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última execução')),
                ('last_status', models.CharField(blank=True, choices=[('', 'Nunca executado'), ('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='', max_length=20, verbose_name='Status da última execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='running', max_length=20, verbose_name='Status')),
                ('triggered_mode', models.CharField(choices=[('schedule', 'Agendado'), ('manual', 'Manual')], default='schedule', max_length=20, verbose_name='Modo de disparo')),
                ('log', models.TextField(blank=True, help_text='Saída de log (stdout/erros) capturada durante a execução.', verbose_name='Log de execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationjob', verbose_name='Automação')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Usuário que disparou manualmente (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Execução de automação',
                'verbose_name_plural': 'Execuções de automação',
                'ordering': ['-started_at'],
            },
        ),
    ]
