# Generated by Django 5.2.8 on 2025-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='command',
            field=models.CharField(blank=True, help_text="Comando a ser executado quando o modo for 'subprocess'. Ex: python C:/Projetos/python/BlueEz2.0/app.py", max_length=512),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='run_mode',
            field=models.CharField(choices=[('module', 'Python (módulo.função)'), ('subprocess', 'Comando externo (subprocess)')], default='module', help_text='Como essa automação será executada.', max_length=20),
        ),
    ]
