# Generated by Django 5.2.8 on 2025-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationjob_command_automationjob_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='entrypoint',
            field=models.CharField(blank=True, help_text="Nome do arquivo principal da automação na pasta do job (por exemplo: main.py). Obrigatório para 'Script externo'.", max_length=255),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='job_type',
            field=models.CharField(choices=[('internal', 'Módulo interno (Python)'), ('external_script', 'Script externo (pasta + venv)')], default='internal', help_text='internal = usa module_path/callable_name dentro do próprio projeto. external_script = usa uma pasta dedicada com venv e um script principal.', max_length=20),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='requirements_filename',
            field=models.CharField(default='requirements.txt', help_text='Nome do arquivo de dependências (requirements) dentro da pasta da automação. Se não existir, o venv será criado sem instalar pacotes extras.', max_length=100),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='use_virtualenv',
            field=models.BooleanField(default=True, help_text='Se marcado, o orquestrador cria um ambiente virtual (.venv) dentro da pasta da automação e instala o requirements lá.'),
        ),
    ]
