# Generated by Django 5.2.8 on 2025-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationjob_entrypoint_automationjob_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='workspace_entrypoint',
            field=models.CharField(blank=True, help_text="Para o modo 'Pacote (pasta + venv)': nome do arquivo Python principal dentro da pasta da automação. Ex: main.py, app.py", max_length=200),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='run_mode',
            field=models.CharField(choices=[('module', 'Python (módulo.função)'), ('subprocess', 'Comando externo (subprocess)'), ('workspace', 'Pacote (pasta + venv)')], default='module', help_text='Como essa automação será executada.', max_length=20),
        ),
    ]
