# Generated by Django 5.2.8 on 2025-11-28 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_automationjob_workspace_entrypoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
