# Generated by Django 5.2.8 on 2025-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_automationrun_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationjob',
            name='callable_name',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='command',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='last_status',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='module_path',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='run_at',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='run_mode',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='workspace_entrypoint',
        ),
        migrations.AddField(
            model_name='automationjob',
            name='external_main_script',
            field=models.CharField(default='main.py', help_text='Ex: main.py, robo.py. A pasta será: automation_jobs/job_<id>/', max_length=200, verbose_name='Arquivo principal (dentro da pasta da automação)'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='one_off_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora única'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='allow_manual',
            field=models.BooleanField(default=True, verbose_name='Permite disparo manual'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='code',
            field=models.SlugField(help_text='Identificador curto, sem espaços. Ex: robo_ixc_login_cliente', max_length=100, unique=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='daily_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário diário'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Pontual'), ('daily', 'Diário')], default='once', max_length=20, verbose_name='Tipo de agendamento'),
        ),
    ]
