# Generated by Django 5.2.8 on 2025-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_remove_automationjob_callable_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationjob',
            name='entrypoint',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='requirements_filename',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='use_virtualenv',
        ),
        migrations.AddField(
            model_name='automationjob',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
