# Generated by Django 5.2.8 on 2025-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_remove_automationjob_entrypoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationjob',
            name='description',
            field=models.TextField(blank=True, help_text='Explicação rápida do que essa automação faz (aparece só na interface).', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='external_main_script',
            field=models.CharField(default='main.py', help_text='Ex: main.py, app.py – arquivo dentro da pasta da automação.', max_length=200, verbose_name='Arquivo principal (Python)'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da automação'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='one_off_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora (pontual)'),
        ),
    ]
