# Generated by Django 5.2.8 on 2025-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_automationjob_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='sector',
            field=models.CharField(choices=[('geral', 'Geral'), ('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('ti', 'TI')], default='geral', help_text='Setor responsável pela automação (usado para filtros futuros).', max_length=50, verbose_name='Setor'),
        ),
    ]
