# Generated by Django 5.2.8 on 2025-12-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_automationjob_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='external_pid',
            field=models.IntegerField(blank=True, help_text='PID do processo da automação (para permitir cancelamento).', null=True, verbose_name='PID do processo externo'),
        ),
    ]
