# Generated by Django 5.2.8 on 2025-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_automationrun_external_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Usado quando o agendamento for 'a cada N minutos'.", null=True, verbose_name='Intervalo (minutos)'),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima execução'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Pontual'), ('daily', 'Diário'), ('interval', 'A cada N minutos')], default='once', max_length=20, verbose_name='Tipo de agendamento'),
        ),
    ]
