# Generated by Django 5.2.8 on 2025-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_automationjob_interval_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='multi_daily_times',
            field=models.CharField(blank=True, help_text='Horários HH:MM separados por vírgula. Ex.: 08:00, 13:00, 18:00', max_length=200, verbose_name='Horários diários (lista)'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Pontual'), ('daily', 'Diário'), ('multi_daily', 'Diário – vários horários'), ('interval', 'A cada N minutos')], default='once', max_length=20, verbose_name='Tipo de agendamento'),
        ),
    ]
