# Generated by Django 5.2.8 on 2025-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_automationjob_multi_daily_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o scheduler não dispara esta automação automaticamente.', verbose_name='Agendamento pausado'),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='code',
            field=models.SlugField(blank=True, help_text='Identificador curto, sem espaços. Ex: robo_ixc_login_cliente', max_length=100, unique=True, verbose_name='Código interno'),
        ),
    ]
