# Generated by Django 5.2.8 on 2025-12-03 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_automationjob_is_paused_alter_automationjob_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('schedule_triggered', 'Agendamento disparado'), ('schedule_skipped_paused', 'Agendamento ignorado (pausado)'), ('schedule_skipped_inactive', 'Agendamento ignorado (inativo)'), ('manual_start', 'Execução manual iniciada'), ('manual_stop', 'Execução manual interrompida'), ('next_run_updated', 'Próxima execução atualizada'), ('scheduler_error', 'Erro no scheduler')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.automationjob')),
                ('run', models.ForeignKey(blank=True, help_text='Execução relacionada (se houver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='automation.automationrun')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Usuário que causou o evento (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
