# Generated by Django 5.2.8 on 2025-12-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('automation', '0014_automationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSectorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('geral', 'Geral'), ('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('ti', 'TI')], max_length=50, verbose_name='Setor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_sector_perms', to='auth.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Permissão de setor de automação',
                'verbose_name_plural': 'Permissões de setor de automação',
                'unique_together': {('group', 'sector')},
            },
        ),
    ]
